ifeq ($(CONFIG_DEBUG_BUILD),y)
  CFLAGS		+=-g
  CXXFLAGS	+=-g
  ASFLAGS		+=-g -Wa,--gdwarf-2
endif

CFLAGS		+=-O$(CONFIG_OPTIMIZE_LEVEL)
CXXFLAGS	+=-O$(CONFIG_OPTIMIZE_LEVEL)
ASFLAGS		+=-O$(CONFIG_OPTIMIZE_LEVEL)
